language: java
jdk:
  - oraclejdk17

script:
  - ./gradlew test

deploy:
  provider: heroku
  api_key:
    secure: 92aa8602-71cf-4f47-93bb-76154f99f3a3
  app: online-shop-ira
  on:
    repo: irasotska/online-shop2